### ISSUE TITLE
seahub doesn't work properly on CentOS 6.5 (python 2.6.6) attribute total_seconds

### ISSUE THREAD

**Issue by khorkin** [haiwen/seahub#283]
There is part of seahub_django_request.log:
2014-09-22 12:05:05,440 [ERROR] django.request:212 handle_uncaught_exception Internal Server Error: /api2/events/
Traceback (most recent call last):
  File "/srv/seafile/seafile-pro-server-3.1.6/seahub/thirdpart/Django-1.5.1-py2.6.egg/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, _callback_args, *_callback_kwargs)
  File "/srv/seafile/seafile-pro-server-3.1.6/seahub/thirdpart/Django-1.5.1-py2.6.egg/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, _args, *_kwargs)
  File "/srv/seafile/seafile-pro-server-3.1.6/seahub/thirdpart/Django-1.5.1-py2.6.egg/django/views/decorators/csrf.py", line 77, in wrapped_view
    return view_func(_args, *_kwargs)
  File "/srv/seafile/seafile-pro-server-3.1.6/seahub/thirdpart/rest_framework/views.py", line 363, in dispatch
    response = self.handle_exception(exc)
  File "/srv/seafile/seafile-pro-server-3.1.6/seahub/thirdpart/rest_framework/views.py", line 360, in dispatch
    response = handler(request, _args, *_kwargs)
  File "/srv/seafile/seafile-pro-server-3.1.6/seahub/seahub/api2/views.py", line 2548, in get
    d['time'] = (local - epoch).total_seconds() \* 1000
AttributeError: 'datetime.timedelta' object has no attribute 'total_seconds'

The possible fix is:
                ## works on python 2.6.7+
                #d['time'] = (local - epoch).total_seconds() \* 1000 
                ## works on python 2.6
                time_diff = local - epoch
                d['time'] = time_diff.seconds + (time_diff.days \* 24 \* 3600)
